### ISSUE TITLE
NameError: name 'SdtFile' is not defined

### ISSUE THREAD

**Issue by Isquare1** [cgohlke/sdtfile#4]
Not sure if it is an actual 'issue', but I figured the question is too niche for stackoverflow so I should ask the module developer themselves :) 

Following the examples on https://pypi.org/project/sdtfile/ : 
```
pip install sdtfile 
import sdtfile 
sdt = SdtFile('image.sdt') 

```
I get the error: 

> NameError: name 'SdtFile' is not defined

sdtfile is indeed installed in site packages, perhaps my import is wrong? 

**Parameters:** 
Anaconda 3
Python 3.7.7
Spyder 4.1.4
Windows 10, 64-bit

**Comment by cgohlke** [comment]
Use `from sdtfile import SdtFile`.
