### ISSUE TITLE
Cannot read an sdt file

### ISSUE THREAD

**Issue by WeiWenKevinChen** [cgohlke/sdtfile#5]
I tried to open an sdt file (FLIM data) using this package but got an error message "There is no item named 'data_block' in the archive". However, I have checked that my file can be opened by the SPCImage software. I am not sure what is the problem. Is it possible for you to try to read one of my FLIM files?

**Comment by cgohlke** [comment]
Please share your SDT file and the version of the software that created the file.

**Comment by WeiWenKevinChen** [comment]
I used Bruker's Prairie View software (customized for 2p-FLIM) to measure the FLIM image of R6G dye (see the data: https://drive.google.com/drive/folders/1n9Q6_BfkUyywMXMxV8C0ry9M56YI6P4Q?usp=sharing). Please let me know if you need further information.

**Comment by cgohlke** [comment]
Should be fixed in v2021.11.18. Thank you for sharing the file.

**Comment by WeiWenKevinChen** [comment]
Thank you so much! It works.
